# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160311_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='source',
            field=models.CharField(default='mixed', max_length=128, verbose_name='Fuente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sighting',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud'),
        ),
    ]
