# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160311_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='SightingFAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Título')),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='clue/')),
            ],
        ),
    ]
