# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160312_0049'),
        ('api', '0005_auto_20160312_0954'),
    ]

    operations = [
    ]
