# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20160401_2252'),
        ('api', '0008_auto_20160401_1721'),
    ]

    operations = [
    ]
