# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_sighting_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='source',
            field=models.CharField(max_length=10, verbose_name='Fuente'),
        ),
    ]
