# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_sighting_user'),
        ('api', '0013_question_order'),
    ]

    operations = [
    ]
