# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_merge'),
        ('api', '0016_auto_20160414_1802'),
    ]

    operations = [
    ]
