# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Respuesta', 'verbose_name_plural': 'Respuestas'},
        ),
        migrations.AlterModelOptions(
            name='expertcomment',
            options={'verbose_name': 'Comentario de experto', 'verbose_name_plural': 'Comentarios de experto'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Localización', 'verbose_name_plural': 'Localizaciones'},
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name': 'Foto', 'verbose_name_plural': 'Fotos'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.AlterModelOptions(
            name='sighting',
            options={'verbose_name': 'Avispamiento', 'verbose_name_plural': 'Avispamientos'},
        ),
        migrations.AlterModelOptions(
            name='sightingfaq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        migrations.AlterModelOptions(
            name='usercomment',
            options={'verbose_name': 'Comentario de usuario', 'verbose_name_plural': 'Comentarios de usuario'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil de usuario', 'verbose_name_plural': 'Perfiles de usuarios'},
        ),
    ]
