# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20160420_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_answer', to='api.Question', verbose_name='Pregunta'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=models.CharField(max_length=128, verbose_name='Respuesta'),
        ),
    ]
