# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20160420_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomment',
            name='moderated',
        ),
    ]
