# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 13:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_usercomment_moderated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='holas', to=settings.AUTH_USER_MODEL),
        ),
    ]
