# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 14:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20160421_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='SightingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Título')),
                ('body', models.TextField(verbose_name='Explicación más detallada')),
                ('quickBody', models.TextField(default='Clic para más información', max_length=128, verbose_name='Breve explicación')),
                ('image', models.ImageField(blank=True, null=True, upload_to='info_images/')),
            ],
            options={
                'verbose_name_plural': 'Info',
                'verbose_name': 'Info',
            },
        ),
        migrations.DeleteModel(
            name='SightingFAQ',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
