# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20160430_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to='api.Location', verbose_name='Localización'),
        ),
    ]
